[project]
name = "markdown2pdf"
version = "0.1.0"
description = "Program for converting markdown to pdf"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyppeteer>=2.0.0",
]

[tool.uv]
package = true

[project.scripts]
markdown2pdf = "md_to_pdf:main"

